AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Event-Driven S3 Upload Notifications system with Go Lambda

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
  NotificationEmail:
    Type: String
    Default: devekkx@gmail.com
    Description: Email address for SNS notifications

Resources:
  # S3 Bucket
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub wk8-eda-${Environment}

  # SNS Topic
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub wk8-eda-topic-${Environment}

  # SNS Subscription
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref NotificationEmail

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub wk8-eda-lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref NotificationTopic

              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub arn:aws:s3:::wk8-eda-${Environment}/*

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # Lambda Function
  NotificationLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: .
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
          EXPECTED_BUCKET: wk8-eda-topic-${Environment}
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub wk8-eda-${Environment}
        - SNSPublishPolicy:
            TopicName: !Sub wk8-eda-topic-${Environment}
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref UploadBucket
  TopicArn:
    Description: ARN of the SNS topic
    Value: !Ref NotificationTopic
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt NotificationLambda.Arn
  LambdaExecutionRoleArn:
    Description: IAM role used by the Lambda function
    Value: !GetAtt LambdaExecutionRole.Arn